# Pull base image.
FROM resin/rpi-raspbian:jessie
# Add our user and group first to make sure their 
# IDs get assigned consistently, regardless of 
# whatever dependencies get added.
RUN groupadd -r mongodb && useradd -r -g mongodb mongodb
# Install MongoDB
RUN apt-get update \
    && apt-get install -y wget mongodb \
    && wget https://www.dropbox.com/s/diex8k6cx5rc95d/core_mongodb.tar.gz \
    && tar -xvzf core_mongodb.tar.gz -C /usr/bin \
    && rm -f core_mongodb.tar.gz \
    && apt-get purge --auto-remove wget \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /var/lib/mongodb 

# Define working directory.
WORKDIR /data

# Configuration.
RUN mkdir -p /data/db /data/configdb \
    && chown -R mongodb:mongodb /data/db /data/configdb
# Define mountable directories.
VOLUME /data/db /data/configdb
# Expose ports.
#   - 27017: process
#   - 28017: http
EXPOSE 27017 28017
# Define default command.
CMD ["mongod","--journal"]
