
let playlists = [ 
    {
            _id:'Chilling',
            title:'Chilling',
            items:[
                {playlist:'Chilling',_id:'axelantunes#1oneverything',artist:'Axel Antunes',album:'#1',title:'On Everything',url:'https://mp3l.jamendo.com/?trackid=1452541&format=mp31&from=app-6fe94250',albumart:'https://imgjam2.jamendo.com/albums/s168/168787/covers/1.200.jpg',artistKey:'axelantunes',albumKey:'#1',groupByKey:'axelantunes'}                                                                                                                                                                                                                                                                                                                                                            
, {playlist:'Chilling',_id:'boomboombeckett20chiudigliocchi',artist:'Boom Boom Beckett',album:'20',title:'Chiudi gli Occhi',url:'https://mp3l.jamendo.com/?trackid=1428062&format=mp31&from=app-6fe94250',albumart:'https://imgjam1.jamendo.com/albums/s166/166470/covers/1.200.jpg',artistKey:'boomboombeckett',albumKey:'20',groupByKey:'boomboombeckett'}                                                                                                                                                                                                                                                                                                                                      
, {playlist:'Chilling',_id:'gillicuddytheyaouhl!mashupssh-dah',artist:'Gillicuddy',album:'The Yaouhl! Mashups',title:'Sh-dah',url:'https://freemusicarchive.org/music/gillicuddy/2013120860050753/03_sh-dah/download',albumart:'https://freemusicarchive.org/file/images/tracks/Track_-_20100110102720054',artistKey:'gillicuddy',albumKey:'theyaouhl!mashups',groupByKey:'gillicuddy'}                                                                                                                                                                                                                                                                                                           
, {playlist:'Chilling',_id:'kinematickitespretty,ugly',artist:'Kinematic',album:'Kites',title:'Pretty, Ugly',url:'https://mp3l.jamendo.com/?trackid=1442032&format=mp31&from=app-6fe94250',albumart:'https://imgjam1.jamendo.com/albums/s167/167814/covers/1.200.jpg',artistKey:'kinematic',albumKey:'kites',groupByKey:'kinematic'}                                                                                                                                                                                                                                                                                                                                                              
, {playlist:'Chilling',_id:'leneztordurootsnrollperverspépère',artist:'Le Nez Tordu',album:'rootsroll',title:'Pervers Pépère',url:'https://mp3l.jamendo.com/?trackid=327457&format=mp31&from=app-6fe94250',albumart:'https://imgjam1.jamendo.com/albums/s43/43867/covers/1.200.jpg',artistKey:'leneztordu',albumKey:'rootsroll',groupByKey:'leneztordu'}                                                                                                                                                                                                                                                                                                                                  
, {playlist:'Chilling',_id:'oceanshiveroutoftimeifwecouldturnbacktime(remix)',artist:'Ocean Shiver',album:'Out of Time',title:'If We Could Turn Back Time (remix)',url:'https://mp3l.jamendo.com/?trackid=1439982&format=mp31&from=app-6fe94250',albumart:'https://imgjam1.jamendo.com/albums/s167/167609/covers/1.200.jpg',artistKey:'oceanshiver',albumKey:'outoftime',groupByKey:'oceanshiver'}                                                                                                                                                                                                                                                                                                
, {playlist:'Chilling',_id:'orestefiengoromalavinia',artist:'Oreste Fiengo',album:'ROMA',title:'LAVINIA',url:'https://mp3l.jamendo.com/?trackid=471394&format=mp31&from=app-6fe94250',albumart:'https://imgjam2.jamendo.com/albums/s55/55747/covers/1.200.jpg',artistKey:'orestefiengo',albumKey:'roma',groupByKey:'orestefiengo'}                                                                                                                                                                                                                                                                                                                                                                
, {playlist:'Chilling',_id:'unicitethemixtapesvol.3daylife',artist:'Unicite',album:'The Mixtapes Vol.3',title:'Daylife',url:'https://mp3l.jamendo.com/?trackid=318599&format=mp31&from=app-6fe94250',albumart:'https://imgjam1.jamendo.com/albums/s43/43076/covers/1.200.jpg',artistKey:'unicite',albumKey:'themixtapesvol.3',groupByKey:'unicite'}                                                                                                                                                                                                                                                                                                                                               
, {playlist:'Chilling',_id:'vitalykim34opozdal',artist:'Vitaly Kim',album:'3 4',title:'Opozdal',url:'https://mp3l.jamendo.com/?trackid=1402585&format=mp31&from=app-6fe94250',albumart:'https://imgjam2.jamendo.com/albums/s164/164077/covers/1.200.jpg',artistKey:'vitalykim',albumKey:'3 4',groupByKey:'vitalykim'}              
            ]
    },

    {
            _id:'CelticFolk',
            title:'Celtic Folk',
            items:[
                {playlist:'Celtic Folk',_id:'adamrsweetcelticado-celticmenkilfenoraset',artist:'Adam R Sweet',album:'Celticado - Celtic Men',title:'Kilfenora Set',url:'https://mp3l.jamendo.com/?trackid=684687&format=mp31&from=app-6fe94250',albumart:'https://imgjam1.jamendo.com/albums/s79/79668/covers/1.200.jpg',artistKey:'adamrsweet',albumKey:'celticado-celticmen',groupByKey:'adamrsweet'} 
, {playlist:'Celtic Folk',_id:'aislinnaislinndropsofbrandy-themountainkid',artist:'Aislinn',album:'Aislinn',title:'Drops of brandy - The mountain kid',url:'https://mp3l.jamendo.com/?trackid=469437&format=mp31&from=app-6fe94250',albumart:'https://imgjam2.jamendo.com/albums/s55/55583/covers/1.200.jpg',artistKey:'aislinn',albumKey:'aislinn',groupByKey:'aislinn'}                                                                                                                                                                                                                                                                                                                         
, {playlist:'Celtic Folk',_id:'aislinnmondayeveningsareyousleepingmaggie',artist:'Aislinn',album:'Monday evenings',title:'Are you sleeping Maggie',url:'https://mp3l.jamendo.com/?trackid=1105633&format=mp31&from=app-6fe94250',albumart:'https://imgjam2.jamendo.com/albums/s132/132026/covers/1.200.jpg',artistKey:'aislinn',albumKey:'mondayevenings',groupByKey:'aislinn'}                                                                                                                                                                                                                                                                                                                   
, {playlist:'Celtic Folk',_id:'aislinnmondayeveningsjuliadelanney-christmaseve-thegreengrovesoferin',artist:'Aislinn',album:'Monday evenings',title:'Julia Delanney - Christmas Eve - The green groves of Erin',url:'https://mp3l.jamendo.com/?trackid=1105637&format=mp31&from=app-6fe94250',albumart:'https://imgjam1.jamendo.com/albums/s132/132026/covers/1.200.jpg',artistKey:'aislinn',albumKey:'mondayevenings',groupByKey:'aislinn'}                                                                                                                                                                                                                                                      
, {playlist:'Celtic Folk',_id:'alérionslesbeauxjourssenvontpassantpluieverte-lunedesaintjean',artist:'Alérions',album:'Les beaux jours s en vont passant',title:'Pluie verte - Lune de saint Jean',url:'https://mp3l.jamendo.com/?trackid=1082960&format=mp31&from=app-6fe94250',albumart:'https://imgjam2.jamendo.com/albums/s129/129051/covers/1.200.jpg',artistKey:'alérions',albumKey:'lesbeauxjourssenvontpassant',groupByKey:'alérion'}                                                                                                                                                                                                                                                  
, {playlist:'Celtic Folk',_id:'briganirishrootsstarofthecountrydown',artist:'Brigan',album:'irish roots',title:'Star of the country down',url:'https://mp3l.jamendo.com/?trackid=584070&format=mp31&from=app-6fe94250',albumart:'https://imgjam1.jamendo.com/albums/s67/67364/covers/1.200.jpg',artistKey:'brigan',albumKey:'irishroots',groupByKey:'brigan'}                                                                                                                                                                                                                                                                                                                                     
, {playlist:'Celtic Folk',_id:'damianobaldonilostdinastyaghrà',artist:'Damiano Baldoni',album:'Lost Dinasty',title:'A Ghrà',url:'https://freemusicarchive.org/music/Damiano_Baldoni/Lost_Dinasty/A_GhrO/download',albumart:'https://freemusicarchive.org/file/images/albums/Damiano_Baldoni_-_Lost_Dinasty_-_20170526173401537.jpg',artistKey:'damianobaldoni',albumKey:'lostdinasty',groupByKey:'damianobaldoni'}                                                                                                                                                                                                                                                                                
, {playlist:'Celtic Folk',_id:'damianobaldonilostdinastycelticwarrior',artist:'Damiano Baldoni',album:'Lost Dinasty',title:'Celtic Warrior',url:'https://freemusicarchive.org/music/Damiano_Baldoni/Lost_Dinasty/Celtic_Warrior/download',albumart:'https://freemusicarchive.org/file/images/albums/Damiano_Baldoni_-_Lost_Dinasty_-_20170526173401537.jpg',artistKey:'damianobaldoni',albumKey:'lostdinasty',groupByKey:'damianobaldoni'}                                                                                                                                                                                                                                                        
, {playlist:'Celtic Folk',_id:'dudeldrumdudeldrumcascade',artist:'DUDELDRUM',album:'DUDELDRUM',title:'Cascade',url:'https://mp3l.jamendo.com/?trackid=761498&format=mp31&from=app-6fe94250',albumart:'https://imgjam2.jamendo.com/albums/s89/89109/covers/1.200.jpg',artistKey:'dudeldrum',albumKey:'dudeldrum',groupByKey:'dudeldrum'}                                                                                                                                                                                                                                                                                                                                                           
, {playlist:'Celtic Folk',_id:'hibaideiedraglennorsonreturnsthevoyageofronniedrew',artist:'Hibai deiedra',album:'Glenn Orson returns',title:'The voyage of Ronnie Drew',url:'https://mp3l.jamendo.com/?trackid=189296&format=mp31&from=app-6fe94250',albumart:'https://imgjam2.jamendo.com/albums/s28/28308/covers/1.200.jpg',artistKey:'hibaideiedra',albumKey:'glennorsonreturns',groupByKey:'hibaideiedra'}                                                                                                                                                                                                                                                                                    
, {playlist:'Celtic Folk',_id:'laguetalarunalglr2007vámonosbaillar',artist:'La Gueta La Runa',album:'LGLR 2007',title:'Vámonos baillar',url:'https://mp3l.jamendo.com/?trackid=127785&format=mp31&from=app-6fe94250',albumart:'https://imgjam2.jamendo.com/albums/s18/18040/covers/1.200.jpg',artistKey:'laguetalaruna',albumKey:'lglr2007',groupByKey:'laguetalaruna'}                                                                                                                                                                                                                                                                                                                           
, {playlist:'Celtic Folk',_id:'saregamacelticstpatrickday-lordmayo(irishtraditional)',artist:'SaReGaMa',album:'Celtic',title:'St Patrick Day - Lord Mayo  (irish traditional)',url:'https://mp3l.jamendo.com/?trackid=905349&format=mp31&from=app-6fe94250',albumart:'https://imgjam2.jamendo.com/albums/s106/106627/covers/1.200.jpg',artistKey:'saregama',albumKey:'celtic',groupByKey:'saregama'}                                                                                                                                                                                                                                                                                              
, {playlist:'Celtic Folk',_id:'woodenlegsifitdoesntlastforever...david&goliath',artist:'Wooden Legs',album:'If it doesnt last forever...',title:'David & Goliath',url:'https://mp3l.jamendo.com/?trackid=768493&format=mp31&from=app-6fe94250',albumart:'https://imgjam2.jamendo.com/albums/s90/90070/covers/1.200.jpg',artistKey:'woodenlegs',albumKey:'ifitdoesntlastforever...',groupByKey:'woodenlegs'}                                                                                                                                                                                                                                                                                    
, {playlist:'Celtic Folk',_id:'woodenlegsifitdoesntlastforever...prideofpimlico',artist:'Wooden Legs',album:'If it doesnt last forever...',title:'Pride of Pimlico',url:'https://mp3l.jamendo.com/?trackid=768550&format=mp31&from=app-6fe94250',albumart:'https://imgjam1.jamendo.com/albums/s90/90070/covers/1.200.jpg',artistKey:'woodenlegs',albumKey:'ifitdoesntlastforever...',groupByKey:'woodenlegs'}     
            ]
    },

    {
            _id:'GetMeMoving',
            title:'Get Me Moving',
            items:[
                {playlist:'Get Me Moving',_id:'akashicrecordsmotivationmotivation',artist:'Akashic Records',album:'Motivation',title:'Motivation',url:'https://mp3l.jamendo.com/?trackid=1295498&format=mp31&from=app-6fe94250',albumart:'https://imgjam2.jamendo.com/albums/s154/154235/covers/1.200.jpg',artistKey:'akashicrecords',albumKey:'motivation',groupByKey:'akashicrecords'}                                                                                                                                                                                                                                                                                                                        
, {playlist:'Get Me Moving',_id:'barefootmccoybyebyebluebirdbyebyebluebird',artist:'Barefoot McCoy',album:'Bye Bye Bluebird',title:'Bye Bye Bluebird',url:'https://mp3l.jamendo.com/?trackid=1428768&format=mp31&from=app-6fe94250',albumart:'https://imgjam2.jamendo.com/albums/s166/166521/covers/1.200.jpg',artistKey:'barefootmccoy',albumKey:'byebyebluebird',groupByKey:'barefootmccoy'}                                                                                                                                                                                                                                                                                                    
, {playlist:'Get Me Moving',_id:'basementbohemianaudiocookbooksunicedtea',artist:'Basement Bohemian',album:'Audio Cookbook',title:'Sun Iced Tea',url:'https://freemusicarchive.org/music/Basement_Bohemian/Audio_Cookbook/Sun_Iced_Tea/download',albumart:'https://freemusicarchive.org/file/images/albums/Audio_Cookbook_-_20170524122552660.jpg',artistKey:'basementbohemian',albumKey:'audiocookbook',groupByKey:'basementbohemian'}                                                                                                                                                                                                                                                           
, {playlist:'Get Me Moving',_id:'colaarsunderhearttotheroofs',artist:'Colaars',album:'Underheart',title:'To The Roofs',url:'https://mp3l.jamendo.com/?trackid=1443264&format=mp31&from=app-6fe94250',albumart:'https://imgjam1.jamendo.com/albums/s167/167916/covers/1.200.jpg',artistKey:'colaars',albumKey:'underheart',groupByKey:'colaars'}                                                                                                                                                                                                                                                                                                                                                   
, {playlist:'Get Me Moving',_id:'deiedraehorzlearenkantuakeuskararenapokalipsia',artist:'Deiedra',album:'Ehorzlearen kantuak',title:'Euskararen apokalipsia',url:'https://mp3l.jamendo.com/?trackid=1390947&format=mp31&from=app-6fe94250',albumart:'https://imgjam2.jamendo.com/albums/s163/163083/covers/1.200.jpg',artistKey:'deiedra',albumKey:'ehorzlearenkantuak',groupByKey:'deiedra'}                                                                                                                                                                                                                                                                                                     
, {playlist:'Get Me Moving',_id:'kinematickitespeyote',artist:'Kinematic',album:'Kites',title:'Peyote',url:'https://mp3l.jamendo.com/?trackid=1442030&format=mp31&from=app-6fe94250',albumart:'https://imgjam2.jamendo.com/albums/s167/167814/covers/1.200.jpg',artistKey:'kinematic',albumKey:'kites',groupByKey:'kinematic'}                                                                                                                                                                                                                                                                                                                                                                    
, {playlist:'Get Me Moving',_id:'lillywolfthispaintedlifestitchesft.shanemaux',artist:'Lilly Wolf',album:'This Painted Life',title:'Stitches ft. Shane MauX',url:'https://mp3l.jamendo.com/?trackid=1093607&format=mp31&from=app-6fe94250',albumart:'https://imgjam2.jamendo.com/albums/s130/130347/covers/1.200.jpg',artistKey:'lillywolf',albumKey:'thispaintedlife',groupByKey:'lillywolf'}                                                                                                                                                                                                                                                                                                    
, {playlist:'Get Me Moving',_id:'the.madpix.projectwishyouwereherewishyouwerehere',artist:'The.madpix.project',album:'Wish You Were Here',title:'Wish You Were Here',url:'https://mp3l.jamendo.com/?trackid=1214935&format=mp31&from=app-6fe94250',albumart:'https://imgjam2.jamendo.com/albums/s145/145774/covers/1.200.jpg',artistKey:'the.madpix.project',albumKey:'wishyouwerehere',groupByKey:'the.madpix.project'}                                                                                                                                                                                                                                                                          
, {playlist:'Get Me Moving',_id:'themoosescandinaviansoundwegotthelove',artist:'The Moose',album:'Scandinavian Sound',title:'We Got The Love',url:'https://mp3l.jamendo.com/?trackid=1414990&format=mp31&from=app-6fe94250',albumart:'https://imgjam1.jamendo.com/albums/s165/165207/covers/1.200.jpg',artistKey:'themoose',albumKey:'scandinaviansound',groupByKey:'themoose'}                                                                                                                                                                                                                                                                                                                   
, {playlist:'Get Me Moving',_id:'themoosescandinaviansoundwithyou',artist:'The Moose',album:'Scandinavian Sound',title:'With You',url:'https://mp3l.jamendo.com/?trackid=1414987&format=mp31&from=app-6fe94250',albumart:'https://imgjam2.jamendo.com/albums/s165/165207/covers/1.200.jpg',artistKey:'themoose',albumKey:'scandinaviansound',groupByKey:'themoose'}                                                                                                                                                                                                                                                                                                                               
, {playlist:'Get Me Moving',_id:'theunderscoreorkestratabledancebelgianwaffles',artist:'The Underscore Orkestra',album:'Table Dance',title:'Belgian Waffles',url:'https://freemusicarchive.org/music/The_Underscore_Orkestra/Table_Dance/The_Underscore_Orkestra_-_Belgian_Waffles/download',albumart:'https://freemusicarchive.org/file/images/albums/The_Underscore_Orkestra_-_Table_Dance_-_20170605203142559.png',artistKey:'theunderscoreorkestra',albumKey:'tabledance',groupByKey:'theunderscoreorkestra'}      
            ]
    },

    {
            _id:'justbeautiful',
            title:'Just Beautiful',
            items:[
                {playlist:'Just Beautiful',_id:'absynthagainstanguishvivaldithefourseasons2.0thefourseason-laprimavera',artist:'Absynth Against Anguish',album:'Vivaldi the four seasons 2.0',title:'The Four Season -  La Primavera',url:'https://mp3l.jamendo.com/?trackid=314992&format=mp31&from=app-6fe94250',albumart:'https://imgjam2.jamendo.com/albums/s42/42601/covers/1.200.jpg',artistKey:'absynthagainstanguish',albumKey:'vivaldithefourseasons2.0',groupByKey:'absynthagainstanguish'}                                                                                                                                                                                                           
, {playlist:'Just Beautiful',_id:'aituaaudiocookbooklemonmeringuepie',artist:'Aitua',album:'Audio Cookbook',title:'Lemon Meringue Pie',url:'https://freemusicarchive.org/music/Aitua/Audio_Cookbook/Lemon_Meringue_Pie/download',albumart:'https://freemusicarchive.org/file/images/albums/Audio_Cookbook_-_20170524122552660.jpg',artistKey:'aitua',albumKey:'audiocookbook',groupByKey:'aitua'}                                                                                                                                                                                                                                                                                                 
, {playlist:'Just Beautiful',_id:'barefootmccoybyebyebluebirdcali',artist:'Barefoot McCoy',album:'Bye Bye Bluebird',title:'Cali',url:'https://mp3l.jamendo.com/?trackid=1428765&format=mp31&from=app-6fe94250',albumart:'https://imgjam1.jamendo.com/albums/s166/166521/covers/1.200.jpg',artistKey:'barefootmccoy',albumKey:'byebyebluebird',groupByKey:'barefootmccoy'}                                                                                                                                                                                                                                                                                                                         
, {playlist:'Just Beautiful',_id:'borrtexabilityability',artist:'Borrtex',album:'Ability',title:'Ability',url:'https://mp3l.jamendo.com/?trackid=1451113&format=mp31&from=app-6fe94250',albumart:'https://imgjam2.jamendo.com/albums/s168/168640/covers/1.200.jpg',artistKey:'borrtex',albumKey:'ability',groupByKey:'borrtex'}                                                                                                                                                                                                                                                                                                                                                                   
, {playlist:'Just Beautiful',_id:'ciannugentliveonwfmusthelongrallywithscottmcdowell-sep17,2013grassabovemyhead',artist:'Cian Nugent',album:'Live on WFMUs The Long Rally with Scott McDowell -Sep 17, 2013',title:'Grass Above My Head',url:'https://freemusicarchive.org/music/Cian_Nugent/Live_on_WFMUs_The_Long_Rally_with_Scott_McDowell_-Sep_17_2013/Cian_Nugent_-_01_-_Grass_Above_My_Head_1150/download',albumart:'https://freemusicarchive.org/file/images/albums/Cian_Nugent_-_Live_on_WFMUs_The_Long_Rally_with_Scott_McDowell_-Sep_17_2013_-_20130919155216993.jpg',artistKey:'ciannugent',albumKey:'liveonwfmusthelongrallywithscottmcdowell-sep17,2013',groupByKey:'ciannugent'} 
, {playlist:'Just Beautiful',_id:'derwaldvolume1ilnord',artist:'derwald',album:'Volume1',title:'Il Nord',url:'https://mp3l.jamendo.com/?trackid=1325467&format=mp31&from=app-6fe94250',albumart:'https://imgjam1.jamendo.com/albums/s156/156953/covers/1.200.jpg',artistKey:'derwald',albumKey:'volume1',groupByKey:'derwald'}                                                                                                                                                                                                                                                                                                                                                                    
, {playlist:'Just Beautiful',_id:'edgarclinksas220foofest2017samplerasmydaydreamsswimby',artist:'Edgar Clinks',album:'AS220 Foo Fest 2017 Sampler',title:'As My Daydreams Swim By',url:'https://freemusicarchive.org/music/Edgar_Clinks/AS220_Foo_Fest_2017_Sampler/05_As_My_Daydreams_Swim_By/download',albumart:'https://freemusicarchive.org/file/images/albums/AS220_-_AS220_Foo_Fest_2017_Sampler_-_20170722135002855.jpg',artistKey:'edgarclinks',albumKey:'as220foofest2017sampler',groupByKey:'edgarclinks'}                                                                                                                                                                              
, {playlist:'Just Beautiful',_id:'laguetalarunalglr2007añadablues',artist:'La Gueta La Runa',album:'LGLR 2007',title:'Añada Blues',url:'https://mp3l.jamendo.com/?trackid=127786&format=mp31&from=app-6fe94250',albumart:'https://imgjam1.jamendo.com/albums/s18/18040/covers/1.200.jpg',artistKey:'laguetalaruna',albumKey:'lglr2007',groupByKey:'laguetalaruna'}                                                                                                                                                                                                                                                                                                                                
, {playlist:'Just Beautiful',_id:'michałjałochowskiwindtoccata/classicalguitarduetwindtoccata/classicalguitarduet/new',artist:'Michał Jałochowski',album:'Wind Toccata / Classical Guitar Duet',title:'Wind Toccata / Classical Guitar Duet / New',url:'https://mp3l.jamendo.com/?trackid=1426196&format=mp31&from=app-6fe94250',albumart:'https://imgjam1.jamendo.com/albums/s166/166278/covers/1.200.jpg',artistKey:'michałjałochowski',albumKey:'windtoccata/classicalguitarduet',groupByKey:'michałjałochowski'}                                                                                                                                                                              
, {playlist:'Just Beautiful',_id:'seastockindiefolkrememberme',artist:'Seastock',album:'Indie Folk',title:'Remember Me',url:'https://mp3l.jamendo.com/?trackid=1227555&format=mp31&from=app-6fe94250',albumart:'https://imgjam2.jamendo.com/albums/s147/147253/covers/1.200.jpg',artistKey:'seastock',albumKey:'indiefolk',groupByKey:'seastock'}                                                                                                                                                                                                                                                                                                                                                 
, {playlist:'Just Beautiful',_id:'squiretuckyearningforbetterdaysyearningforbetterdays',artist:'Squire Tuck',album:'Yearning for Better Days',title:'Yearning for Better Days',url:'https://freemusicarchive.org/music/Squire_Tuck/Yearning_for_Better_Days/Yearning_for_Better_Days/download',albumart:'https://freemusicarchive.org/file/images/albums/Squire_Tuck_-_Yearning_for_Better_Days_-_20170808153910541.jpg',artistKey:'squiretuck',albumKey:'yearningforbetterdays',groupByKey:'squiretuck'}                                                                                                                                                                                         
, {playlist:'Just Beautiful',_id:'therabbittsavocadogingertreeavocadogingertree',artist:'The Rabbitts',album:'Avocado Ginger Tree',title:'Avocado Ginger Tree',url:'https://mp3l.jamendo.com/?trackid=1447219&format=mp31&from=app-6fe94250',albumart:'https://imgjam2.jamendo.com/albums/s168/168269/covers/1.200.jpg',artistKey:'therabbitts',albumKey:'avocadogingertree',groupByKey:'therabbitts'}                                                                                                                                                                                                                                                                                            
, {playlist:'Just Beautiful',_id:'thorwaldodindigitallyreborn(vivaldisfourseasonsinelectronicalflavor)movimento5adagiopresto-summer',artist:'Thorwald Odin',album:'Digitally Reborn (Vivaldis Four Seasons in electronical flavor)',title:'Movimento 5 Adagio Presto - Summer',url:'https://mp3l.jamendo.com/?trackid=949676&format=mp31&from=app-6fe94250',albumart:'https://imgjam1.jamendo.com/albums/s111/111656/covers/1.200.jpg',artistKey:'thorwaldodin',albumKey:'digitallyreborn(vivaldisfourseasonsinelectronicalflavor)',groupByKey:'thorwaldodin'}    
            ]
    },

    {
            _id:'worldmusic',
            title:'World Music',
            items:[
                {playlist:'World Music',_id:'caligineonasteadydietofhash,bread,&saltmεπιάνουνεζαλάδες',artist:'Caligine',album:'On A Steady Diet of Hash, Bread, & Salt',title:'Mε Πιάνουνε Ζαλάδες',url:'https://freemusicarchive.org/music/Caligine/On_A_Steady_Diet_of_Hash_Bread__Salt/soundeyet_-_ON_A_STEADY_DIET_OF_HASH_BREAD__SALT_-_15_M__/download',albumart:'https://freemusicarchive.org/file/images/tracks/Track_-_20120712110518503',artistKey:'caligine',albumKey:'onasteadydietofhash,bread,&salt',groupByKey:'caligine'}                                                                                                                                                                      
, {playlist:'World Music',_id:'edwardjayakodyakurumaekinaelanduowiti',artist:'Edward Jayakody',album:'Akuru Maeki Nae',title:'Landu Owiti',url:'https://freemusicarchive.org/music/Edward_Jayakody/Akuru_Maeki_Nae/Landu_Owiti/download',albumart:'images/tracks/Track_-_2017080140717526',artistKey:'edwardjayakody',albumKey:'akurumaekinae',groupByKey:'edwardjayakody'}                                                                                                                                                                                                                                                                                                                       
, {playlist:'World Music',_id:'kevinmacleodglobalsamplertikopia',artist:'Kevin MacLeod',album:'Global Sampler',title:'Tikopia',url:'https://freemusicarchive.org/music/Kevin_MacLeod/Global_Sampler/Tikopia/download',albumart:'https://freemusicarchive.org/file/images/albums/Kevin_MacLeod_-_Global_Sampler_-_20110715144602456.jpg',artistKey:'kevinmacleod',albumKey:'globalsampler',groupByKey:'kevinmacleod'}                                                                                                                                                                                                                                                                              
, {playlist:'World Music',_id:'samshalabionasteadydietofhash,bread,&saltrebetikaud',artist:'Sam Shalabi',album:'On A Steady Diet of Hash, Bread, & Salt',title:'Rebetikaud',url:'https://freemusicarchive.org/music/Sam_Shalabi/On_A_Steady_Diet_of_Hash_Bread__Salt/soundeyet_-_ON_A_STEADY_DIET_OF_HASH_BREAD__SALT_-_08_Rebetikaud/download',albumart:'https://freemusicarchive.org/file/images/tracks/Track_-_20120712111156339',artistKey:'samshalabi',albumKey:'onasteadydietofhash,bread,&salt',groupByKey:'samshalabi'}                                                                                                                                                                   
, {playlist:'World Music',_id:'thekyotoconnectionthefirstvoyagedanceofthemidnightwind',artist:'The Kyoto Connection',album:'The First Voyage',title:'Dance of the midnight wind',url:'https://mp3l.jamendo.com/?trackid=585182&format=mp31&from=app-6fe94250',albumart:'https://imgjam1.jamendo.com/albums/s67/67509/covers/1.200.jpg',artistKey:'thekyotoconnection',albumKey:'thefirstvoyage',groupByKey:'thekyotoconnection'}                                                                                                                                                                                                                                                                  
, {playlist:'World Music',_id:'thesoundsoftaraabzanzibar,newyorkmahabawatakanini',artist:'The Sounds of Taraab',album:'Zanzibar, New York',title:'Mahaba Wa Taka Nini',url:'https://freemusicarchive.org/music/The_Sounds_of_Taraab/Zanzibar_New_York/Mahaba_Wa_Taka_Nini/download',albumart:'https://freemusicarchive.org/file/images/artists/The_Sounds_of_Taraab_-_2009113015730135.jpg',artistKey:'thesoundsoftaraab',albumKey:'zanzibar,newyork',groupByKey:'thesoundsoftaraab'}                                                                                                                                                                                                             
, {playlist:'World Music',_id:'theunderscoreorkestraalittlebitofmagicineverybatch...05bmklezmer',artist:'The Underscore Orkestra',album:'A Little Bit of Magic in Every Batch...',title:'05 Bm Klezmer',url:'https://freemusicarchive.org/music/The_Underscore_Orkestra/A_Little_Bit_of_Magic_in_Every_Batch/05_Bm_Klezmer/download',albumart:'https://freemusicarchive.org/file/images/albums/The_Underscore_Orkestra_-_A_Little_Bit_of_Magic_in_Every_Batch_-_20141217223838757.jpg',artistKey:'theunderscoreorkestra',albumKey:'alittlebitofmagicineverybatch...',groupByKey:'theunderscoreorkestra'}                                                                                          
, {playlist:'World Music',_id:'theunderscoreorkestranomoneynohoneyallwegotisusamariszi',artist:'The Underscore Orkestra',album:'No Money No Honey All We Got Is Us',title:'Amari Szi',url:'https://freemusicarchive.org/music/The_Underscore_Orkestra/No_Money_No_Honey_All_We_Got_Is_Us/Amari_Szi/download',albumart:'https://freemusicarchive.org/file/images/albums/The_Underscore_Orkestra_-_No_Money_No_Honey_All_We_Got_Is_Us_-_2009113014023807.jpg',artistKey:'theunderscoreorkestra',albumKey:'nomoneynohoneyallwegotisus',groupByKey:'theunderscoreorkestra'}                                                                                                                           
, {playlist:'World Music',_id:'theunderscoreorkestratheextraordinaryadventuresof...romanianhora',artist:'The Underscore Orkestra',album:'The ExtraOrdinary Adventures of...',title:'Romanian Hora',url:'https://freemusicarchive.org/music/The_Underscore_Orkestra/The_ExtraOrdinary_Adventures_of/08_Rumanian_Hora/download',albumart:'https://freemusicarchive.org/file/images/albums/The_Underscore_Orkestra_-_The_ExtraOrdinary_Adventures_of_-_20141217224622097.jpg',artistKey:'theunderscoreorkestra',albumKey:'theextraordinaryadventuresof...',groupByKey:'theunderscoreorkestra'}                                                                                                       
, {playlist:'World Music',_id:'unicitethemixtapesdirectganesh',artist:'Unicite',album:'The Mixtapes',title:'Direct Ganesh',url:'https://mp3l.jamendo.com/?trackid=238578&format=mp31&from=app-6fe94250',albumart:'https://imgjam1.jamendo.com/albums/s34/34766/covers/1.200.jpg',artistKey:'unicite',albumKey:'themixtapes',groupByKey:'unicite'}                                                                                                                                                                                                                                                                                                                                                 
, {playlist:'World Music',_id:'zinaidatrokaisoulsandthespiritofrussianlove',artist:'Zinaida Trokai',album:'Soul Sand',title:'The Spirit of Russian Love',url:'https://freemusicarchive.org/music/Zinaida_Trokai/Soul_Sand/Zinaida_Trokai_-_The_Spirit_of_Russian_Love/download',albumart:'https://freemusicarchive.org/file/images/tracks/Track_-_20160919154341029',artistKey:'zinaidatrokai',albumKey:'soulsand',groupByKey:'zinaidatrokai'}                                                                                                                                     
            ]
    },
       {_id:'freddofrogvideo','title':'Videos',items:[
        {_id:'freddofrogvideo1',title:'Big Buck Bunny',url:'http://commondatastorage.googleapis.com/gtv-videos-bucket/big_buck_bunny_1080p.mp4',albumart:'images/BigBuckBunny.jpg',type:'video'},
        {_id:'freddofrogvideo2',title:'Elephant Dream',url:'http://commondatastorage.googleapis.com/gtv-videos-bucket/ED_1280.mp4',albumart:'images/ElephantsDream.jpg',type:'video'},
        {_id:'freddofrogvideo3',title:'Tears of Steel',url:'http://commondatastorage.googleapis.com/gtv-videos-bucket/tears_of_steel_1080p.mov',albumart:'images/TearsOfSteel.jpg',type:'video'},
        {_id:'freddofrogvideo4',title:'Reel 2012',url:'http://commondatastorage.googleapis.com/gtv-videos-bucket/reel_2012_1280x720.mp4',albumart:'images/reel.jpg',type:'video'},
        {_id:'freddofrogvideo5',title:'Google I/O 2011 Audio',url:'http://commondatastorage.googleapis.com/gtv-videos-bucket/Google%20IO%202011%2045%20Min%20Walk%20Out.mp3',albumart:'images/google-io-2011.jpg',type:'audio'},
    
    ]},
    
    {
        _id:'youtube',
        title:'YouTube',
        items:[
            {_id:'yt1', title:'Steve Bags - TetraOrbliss', url:'https://www.youtube.com/watch?v=ZqH2GjX9Sos',albumart:'',type:'video'},
            {_id:'yt2', title:'Vsauce - Which way is down ?',url:'https://www.youtube.com/watch?v=Xc4xYacTu-E', albumart:'',type:'video'}
        ]
        
    }
];

//var ObjectId = require('mongodb').ObjectID;
//import ObjectId from 'objectid-browser';
//var ObjectId = require('objectid-browser').ObjectId;
var ObjectId = require('objectid-browser');
console.log(['OBJID',ObjectId])

playlists.map(function(val) {
    val._id = ObjectId();
  //  val.isSample = true;
    val.items.map(function(ival) {
        ival._id = new ObjectId();
        return null;
    });
    return null;
})
module.exports=playlists;
//export default playlists;
